### ISSUE TITLE
Allow me to edit the details of my podcast episode

### ISSUE THREAD

**Issue by kookster** [PRX/www.prx.org#212] opened 2015-04-15 20:17 UTC
* Title
* Description
* File size (auto populate, allow override)
* Duration (auto populated, allow override)
* Author
* Keywords
* Subtitle
* Summary
* Explicit
* Image 1400x1400

**Comment by driki** [comment] 2015-08-24 15:00
Closing this issue as it is a duplicate of #281and moving the details from this issue into that issue.

**Closed by driki** 2015-08-24 15:00 UTC
