### ISSUE TITLE
Show me if there is a problem with my audio files

### ISSUE THREAD

**Issue by driki** [PRX/www.prx.org#232] opened 2015-04-23 13:48 UTC
Did I upload an invalid audio file? Is it at the wrong bitrate? Too large? Wrong encoding type?

**Comment by farski** [comment] 2015-08-06 14:27
@chrisrhoden @kookster To what extent are we handling audio validation for this milestone, and is it happening client-side or server-side?

**Comment by kookster** [comment] 2015-08-06 17:27
I don't think it should be.

I didn't realize that a validation related ticket was in this milestone - in fact there are several other backlogged tickets I also don't think were discussed as being part of the scope of this milestone.

The current/expired milestone should be reviewed, and new ones created for the remaining work.

**Comment by driki** [comment] 2015-08-06 17:40
@kookster I'm ok with ejecting this ticket from this milestone, as we'll have more control over the audio that is being uploaded. This is the filter that I have applied to Waffle to view the current milestone: https://waffle.io/prx/meta.prx.org?milestone=Podcast%20Feeds,Podcast%20publishing are there other tickets in there that feel extraneous to this milestone or that should be pushed to a future milestone? If so, please flag them with a comment and I'll review/move.

**Comment by kookster** [comment] 2015-08-06 17:46
I was only looking at the 'publishing' milestone, but was thinking about the ones tagged as `enhancements` in the backlog column.

From a process standpoint, I think we need to start closing out milestones, and opening new ones - these have both persisted and overlapped for awhile, seems to defeat the purpose of the milestones, we could just use the waffle columns.

**Comment by kookster** [comment] 2015-08-21 16:05
@driki I propose this covers front-end validations for the audio, and display of errors in that validation.

More complete processing should be done on the backend/cms as in ticket
https://github.com/PRX/cms.prx.org/issues/122

**Comment by farski** [comment] 2015-09-02 19:55
@driki Just want to make sure this is still a target for Transistor milestone

**Comment by driki** [comment] 2015-09-02 20:48
The front end validations that Andrew mentioned, yes. Similar to what was in place for the demo back in October 2014.

**Comment by farski** [comment] 2015-09-02 20:54
I think the validations that were happening in the demo were broadcast-focused. @kookster @chrisrhoden what podcast validations do we want to do client side? File type, seems obvious. Any quality checking? Duration sanity check? Etc?

**Comment by kookster** [comment] 2015-09-02 21:18
I don't know exactly.
Certainly type, and sure, a duration sanity check.
The quality issue gets to a combo of # of channels, bit rate and sample rate, and I don't know if we have a standard per se.

I think we could validate for each channel of an mp3 being at least 32k, and 44.1 sample rate, or establish per podcast standards. Both would be good - having a bare minimum, and then also establishing a standard for a particular show.

**Comment by farski** [comment] 2015-09-03 14:01
The other thing to consider is that some of these validations basically made using the site impossible, because they were so slow. Aside from a deep dive in Aurora I'm not sure how to address that. Are there any alternative libraries to look at?

**Comment by kookster** [comment] 2015-09-03 14:48
I did some research on this last night.

For basic 'is this an mp3', size, and duration you can use more basic file
methods:

https://jsfiddle.net/derickbailey/s4P2v/

You can get better info (sample rate, bit rate, channels) from the now
almost standard Web Audio API, and those may be faster than aurora.js

I have found no better alternative to aurora for non standard encodings,
like flac and mp2.

There may be some changes to how we use aurora as well - I tested it with
some fairly large mp3 and flac files, and it was not that slow, so I
suspect there is something else involved here.

**Comment by kookster** [comment] 2015-09-03 14:49
also, I did some tests using `createObjectURL` for accessing the form file input, and that seemed to be faster for some purposes, not sure we are using that.

**Comment by farski** [comment] 2015-09-03 17:45
@chrisrhoden Is the expected behavior here just that if files don't validate the save/publish are blocked?

**Comment by kookster** [comment] 2015-09-03 19:48
These validations can occur before the file is even uploaded - they occur after the file is selected. I would think we could validate before upload even occurs, before save or publish, no?

**Closed** 2016-09-15 21:09 UTC
